import {
  iconAccept,
  iconAddEvent,
  iconAddImage,
  iconAddVideo,
  iconComment,
  iconDate,
  iconEmoji,
  iconFriend,
  iconGift,
  iconGroup,
  iconHome,
  iconLike,
  iconLink,
  iconMap,
  iconMessage,
  iconMore,
  iconNoAvatar,
  iconNotification,
  iconPeople,
  iconPoll,
  iconReject,
  iconSchool,
  iconSearch,
  iconShare,
  iconStory,
  iconWork,
} from "@/constants";
import { IconsTypes } from "@/types/Icons.type";

export const icons: IconsTypes = {
  home: iconHome,
  friends: iconFriend,
  groups: iconGroup,
  stories: iconStory,
  login: iconNoAvatar,
  people: iconPeople,
  message: iconMessage,
  notification: iconNotification,
  search: iconSearch,
  emoji: iconEmoji,
  addImage: iconAddImage,
  addVideo: iconAddVideo,
  addEvent: iconAddEvent,
  poll: iconPoll,
  more: iconMore,
  like: iconLike,
  comment: iconComment,
  share: iconShare,
  accept: iconAccept,
  reject: iconReject,
  gift: iconGift,
  map: iconMap,
  school: iconSchool,
  work: iconWork,
  link: iconLink,
  date: iconDate,
} as const;
