import {
  iconAddEvent,
  iconAddImage,
  iconAddVideo,
  iconComment,
  iconEmoji,
  iconFriend,
  iconGroup,
  iconHome,
  iconLike,
  iconMessage,
  iconMore,
  iconNoAvatar,
  iconNotification,
  iconPeople,
  iconPoll,
  iconSearch,
  iconShare,
  iconStory,
} from "@/constants";
import { IconsTypes } from "@/types/Icons.type";

export const icons: IconsTypes = {
  home: iconHome,
  friends: iconFriend,
  groups: iconGroup,
  stories: iconStory,
  login: iconNoAvatar,
  people: iconPeople,
  message: iconMessage,
  notification: iconNotification,
  search: iconSearch,
  emoji: iconEmoji,
  addImage: iconAddImage,
  addVideo: iconAddVideo,
  addEvent: iconAddEvent,
  poll: iconPoll,
  more: iconMore,
  like: iconLike,
  comment: iconComment,
  share: iconShare,
} as const;
