export type IconsTypes = {
  home: string;
  friends: string;
  groups: string;
  stories: string;
  login: string;
  people: string;
  message: string;
  notification: string;
  search: string;
  emoji: string;
  addImage: string;
  addVideo: string;
  addEvent: string;
  poll: string;
  more: string;
  like: string;
  comment: string;
  share: string;
};
